replicaCount: 1

image:
  repository: 952729869933.dkr.ecr.eu-west-1.amazonaws.com/passport
  tag: latest
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: NodePort
  port: 80

ingress:
  enabled: true
  annotations:
  paths:
    - /
  hosts:
    - passport.bysidecar.me
  tls:
    - secretName: tls-passport-bysidecar-me
      hosts:
        - passport.bysidecar.me
env:
- name: DB_HOST
  value: "passport.c848y92oajny.eu-west-1.rds.amazonaws.com"
- name: DB_PORT
  value: "3306"
- name: DB_NAME
  value: "passport_pre"
- name: DB_USER
  valueFrom:
    secretKeyRef:
      name: passport-database
      key: user
- name: DB_PASS
  valueFrom:
    secretKeyRef:
      name: passport-database
      key: pass

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
