replicaCount: 1

image:
  repository: repo_url/managerid
  tag: latest
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: NodePort
  port: 80

ingress:
  enabled: true
  annotations:
  paths:
    - /
  hosts:
    - managerid.josedelrio.me
  tls:
    - secretName: tls-managerid-josedelrio-me
      hosts:
        - managerid.josedelrio.me
env:
- name: DB_HOST
  value: host_db
- name: DB_PORT
  value: "3306"
- name: DB_NAME
  value: manageriddb
- name: DB_USER
  valueFrom:
    secretKeyRef:
      name: managerid-database
      key: user
- name: DB_PASS
  valueFrom:
    secretKeyRef:
      name: managerid-database
      key: pass

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
