version: 0.2

env:
  variables:
    PACKAGE: "github.com/josedelrio85/managerid"
    DB_PORT: "3306"
    DB_HOST: "127.0.0.1"
    DB_USER: test
    DB_PASS: test
    DB_NAME: test
    
phases:
  install:
    commands:
      - echo CODEBUILD_SRC_DIR - $CODEBUILD_SRC_DIR
      - echo GOPATH - $GOPATH
      - echo GOROOT - $GOROOT

      - echo Create dir in GOPATH for sources
      - mkdir -p ${GOPATH}/src/${PACKAGE}

      - echo Copy source files into GOPATH
      - echo cp -a ${CODEBUILD_SRC_DIR}/. ${GOPATH}/src/${PACKAGE}
      - cp -a ${CODEBUILD_SRC_DIR}/. ${GOPATH}/src/${PACKAGE}

      - echo Get into folder
      - cd ${GOPATH}/src/${PACKAGE} 
      
      - echo Running tests 1...
      - go vet -mod=vendor ./...
      
      - echo Running tests 2...
      - go test -mod=vendor -v ./...

  build:
    commands:
      - cd ${GOPATH}/src/${PACKAGE} && go get -d -v && go build -o ${CODEBUILD_SRC_DIR}/application